# config.yaml
# A default config file. For the full summary of each field, 
# read src/bs/ts/example/configs/verbose.yaml

operation:
  maxSize: 1048576

block:
  maxSize: 134217728
  maxOperationCount: 128
  difficultyMode: Static
  difficultyTargetValue: 16

blockchain:
  broadcastMode: Async